/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationQueueRouteImport } from './routes/validation-queue'
import { Route as UndoRouteImport } from './routes/undo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminValidationQueueIndexRouteImport } from './routes/admin/validation-queue/index'
import { Route as AdminUndoIndexRouteImport } from './routes/admin/undo/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminResearchersIndexRouteImport } from './routes/admin/researchers/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminImportIndexRouteImport } from './routes/admin/import/index'
import { Route as AdminGroupsIndexRouteImport } from './routes/admin/groups/index'
import { Route as PublicResearchersIndexRouteImport } from './routes/_public/researchers/index'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public/projects/index'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products/index'
import { Route as PublicGroupsIndexRouteImport } from './routes/_public/groups/index'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsDisplayRouteImport } from './routes/admin/settings/display'
import { Route as AdminSettingsAppearanceRouteImport } from './routes/admin/settings/appearance'
import { Route as AdminSettingsAccountRouteImport } from './routes/admin/settings/account'
import { Route as AdminResearchersIdRouteImport } from './routes/admin/researchers/$id'
import { Route as AdminProjectsIdRouteImport } from './routes/admin/projects/$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminGroupsIdRouteImport } from './routes/admin/groups/$id'
import { Route as PublicResearchersIdRouteImport } from './routes/_public/researchers/$id'
import { Route as PublicProjectsIdRouteImport } from './routes/_public/projects/$id'
import { Route as PublicProductsIdRouteImport } from './routes/_public/products/$id'
import { Route as PublicGroupsIdRouteImport } from './routes/_public/groups/$id'

const ValidationQueueRoute = ValidationQueueRouteImport.update({
  id: '/validation-queue',
  path: '/validation-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const UndoRoute = UndoRouteImport.update({
  id: '/undo',
  path: '/undo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminValidationQueueIndexRoute =
  AdminValidationQueueIndexRouteImport.update({
    id: '/validation-queue/',
    path: '/validation-queue/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUndoIndexRoute = AdminUndoIndexRouteImport.update({
  id: '/undo/',
  path: '/undo/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminResearchersIndexRoute = AdminResearchersIndexRouteImport.update({
  id: '/researchers/',
  path: '/researchers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportIndexRoute = AdminImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsIndexRoute = AdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicResearchersIndexRoute = PublicResearchersIndexRouteImport.update({
  id: '/researchers/',
  path: '/researchers/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicGroupsIndexRoute = PublicGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsDisplayRoute = AdminSettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAppearanceRoute = AdminSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminResearchersIdRoute = AdminResearchersIdRouteImport.update({
  id: '/researchers/$id',
  path: '/researchers/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsIdRoute = AdminGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicResearchersIdRoute = PublicResearchersIdRouteImport.update({
  id: '/researchers/$id',
  path: '/researchers/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProjectsIdRoute = PublicProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicGroupsIdRoute = PublicGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/undo': typeof UndoRoute
  '/validation-queue': typeof ValidationQueueRoute
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/system': typeof AdminSystemRoute
  '/admin/': typeof AdminIndexRoute
  '/groups/$id': typeof PublicGroupsIdRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/projects/$id': typeof PublicProjectsIdRoute
  '/researchers/$id': typeof PublicResearchersIdRoute
  '/admin/groups/$id': typeof AdminGroupsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/researchers/$id': typeof AdminResearchersIdRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/groups/': typeof PublicGroupsIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/projects/': typeof PublicProjectsIndexRoute
  '/researchers/': typeof PublicResearchersIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/import/': typeof AdminImportIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/researchers/': typeof AdminResearchersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/undo/': typeof AdminUndoIndexRoute
  '/admin/validation-queue/': typeof AdminValidationQueueIndexRoute
}
export interface FileRoutesByTo {
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/undo': typeof UndoRoute
  '/validation-queue': typeof ValidationQueueRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin/system': typeof AdminSystemRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/groups/$id': typeof PublicGroupsIdRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/projects/$id': typeof PublicProjectsIdRoute
  '/researchers/$id': typeof PublicResearchersIdRoute
  '/admin/groups/$id': typeof AdminGroupsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/researchers/$id': typeof AdminResearchersIdRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/groups': typeof PublicGroupsIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/projects': typeof PublicProjectsIndexRoute
  '/researchers': typeof PublicResearchersIndexRoute
  '/admin/groups': typeof AdminGroupsIndexRoute
  '/admin/import': typeof AdminImportIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/researchers': typeof AdminResearchersIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/undo': typeof AdminUndoIndexRoute
  '/admin/validation-queue': typeof AdminValidationQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/undo': typeof UndoRoute
  '/validation-queue': typeof ValidationQueueRoute
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/admin/system': typeof AdminSystemRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/groups/$id': typeof PublicGroupsIdRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
  '/_public/projects/$id': typeof PublicProjectsIdRoute
  '/_public/researchers/$id': typeof PublicResearchersIdRoute
  '/admin/groups/$id': typeof AdminGroupsIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/researchers/$id': typeof AdminResearchersIdRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/_public/groups/': typeof PublicGroupsIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
  '/_public/researchers/': typeof PublicResearchersIndexRoute
  '/admin/groups/': typeof AdminGroupsIndexRoute
  '/admin/import/': typeof AdminImportIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/researchers/': typeof AdminResearchersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/undo/': typeof AdminUndoIndexRoute
  '/admin/validation-queue/': typeof AdminValidationQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/import'
    | '/settings'
    | '/undo'
    | '/validation-queue'
    | '/admin/settings'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/system'
    | '/admin/'
    | '/groups/$id'
    | '/products/$id'
    | '/projects/$id'
    | '/researchers/$id'
    | '/admin/groups/$id'
    | '/admin/products/$id'
    | '/admin/projects/$id'
    | '/admin/researchers/$id'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/groups/'
    | '/products/'
    | '/projects/'
    | '/researchers/'
    | '/admin/groups/'
    | '/admin/import/'
    | '/admin/products/'
    | '/admin/projects/'
    | '/admin/researchers/'
    | '/admin/settings/'
    | '/admin/undo/'
    | '/admin/validation-queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/import'
    | '/settings'
    | '/undo'
    | '/validation-queue'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin/system'
    | '/'
    | '/admin'
    | '/groups/$id'
    | '/products/$id'
    | '/projects/$id'
    | '/researchers/$id'
    | '/admin/groups/$id'
    | '/admin/products/$id'
    | '/admin/projects/$id'
    | '/admin/researchers/$id'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/groups'
    | '/products'
    | '/projects'
    | '/researchers'
    | '/admin/groups'
    | '/admin/import'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/researchers'
    | '/admin/settings'
    | '/admin/undo'
    | '/admin/validation-queue'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/import'
    | '/settings'
    | '/undo'
    | '/validation-queue'
    | '/admin/settings'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/admin/system'
    | '/_public/'
    | '/admin/'
    | '/_public/groups/$id'
    | '/_public/products/$id'
    | '/_public/projects/$id'
    | '/_public/researchers/$id'
    | '/admin/groups/$id'
    | '/admin/products/$id'
    | '/admin/projects/$id'
    | '/admin/researchers/$id'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/_public/groups/'
    | '/_public/products/'
    | '/_public/projects/'
    | '/_public/researchers/'
    | '/admin/groups/'
    | '/admin/import/'
    | '/admin/products/'
    | '/admin/projects/'
    | '/admin/researchers/'
    | '/admin/settings/'
    | '/admin/undo/'
    | '/admin/validation-queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ImportRoute: typeof ImportRoute
  SettingsRoute: typeof SettingsRoute
  UndoRoute: typeof UndoRoute
  ValidationQueueRoute: typeof ValidationQueueRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation-queue': {
      id: '/validation-queue'
      path: '/validation-queue'
      fullPath: '/validation-queue'
      preLoaderRoute: typeof ValidationQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undo': {
      id: '/undo'
      path: '/undo'
      fullPath: '/undo'
      preLoaderRoute: typeof UndoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/validation-queue/': {
      id: '/admin/validation-queue/'
      path: '/validation-queue'
      fullPath: '/admin/validation-queue/'
      preLoaderRoute: typeof AdminValidationQueueIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/undo/': {
      id: '/admin/undo/'
      path: '/undo'
      fullPath: '/admin/undo/'
      preLoaderRoute: typeof AdminUndoIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/researchers/': {
      id: '/admin/researchers/'
      path: '/researchers'
      fullPath: '/admin/researchers/'
      preLoaderRoute: typeof AdminResearchersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/import/': {
      id: '/admin/import/'
      path: '/import'
      fullPath: '/admin/import/'
      preLoaderRoute: typeof AdminImportIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups/': {
      id: '/admin/groups/'
      path: '/groups'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AdminGroupsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/researchers/': {
      id: '/_public/researchers/'
      path: '/researchers'
      fullPath: '/researchers/'
      preLoaderRoute: typeof PublicResearchersIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/groups/': {
      id: '/_public/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof PublicGroupsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/display': {
      id: '/admin/settings/display'
      path: '/display'
      fullPath: '/admin/settings/display'
      preLoaderRoute: typeof AdminSettingsDisplayRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/researchers/$id': {
      id: '/admin/researchers/$id'
      path: '/researchers/$id'
      fullPath: '/admin/researchers/$id'
      preLoaderRoute: typeof AdminResearchersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups/$id': {
      id: '/admin/groups/$id'
      path: '/groups/$id'
      fullPath: '/admin/groups/$id'
      preLoaderRoute: typeof AdminGroupsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/researchers/$id': {
      id: '/_public/researchers/$id'
      path: '/researchers/$id'
      fullPath: '/researchers/$id'
      preLoaderRoute: typeof PublicResearchersIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/projects/$id': {
      id: '/_public/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof PublicProjectsIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/groups/$id': {
      id: '/_public/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof PublicGroupsIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicGroupsIdRoute: typeof PublicGroupsIdRoute
  PublicProductsIdRoute: typeof PublicProductsIdRoute
  PublicProjectsIdRoute: typeof PublicProjectsIdRoute
  PublicResearchersIdRoute: typeof PublicResearchersIdRoute
  PublicGroupsIndexRoute: typeof PublicGroupsIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
  PublicResearchersIndexRoute: typeof PublicResearchersIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicGroupsIdRoute: PublicGroupsIdRoute,
  PublicProductsIdRoute: PublicProductsIdRoute,
  PublicProjectsIdRoute: PublicProjectsIdRoute,
  PublicResearchersIdRoute: PublicResearchersIdRoute,
  PublicGroupsIndexRoute: PublicGroupsIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
  PublicResearchersIndexRoute: PublicResearchersIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsDisplayRoute: typeof AdminSettingsDisplayRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsDisplayRoute: AdminSettingsDisplayRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminGroupsIdRoute: typeof AdminGroupsIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminResearchersIdRoute: typeof AdminResearchersIdRoute
  AdminGroupsIndexRoute: typeof AdminGroupsIndexRoute
  AdminImportIndexRoute: typeof AdminImportIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminResearchersIndexRoute: typeof AdminResearchersIndexRoute
  AdminUndoIndexRoute: typeof AdminUndoIndexRoute
  AdminValidationQueueIndexRoute: typeof AdminValidationQueueIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminGroupsIdRoute: AdminGroupsIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminResearchersIdRoute: AdminResearchersIdRoute,
  AdminGroupsIndexRoute: AdminGroupsIndexRoute,
  AdminImportIndexRoute: AdminImportIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminResearchersIndexRoute: AdminResearchersIndexRoute,
  AdminUndoIndexRoute: AdminUndoIndexRoute,
  AdminValidationQueueIndexRoute: AdminValidationQueueIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ImportRoute: ImportRoute,
  SettingsRoute: SettingsRoute,
  UndoRoute: UndoRoute,
  ValidationQueueRoute: ValidationQueueRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
